[project]
name = "bast3st"
version = "0.1.0"
description = "Specification of unit tests of .sb3-programs for a Bast3St server"
readme = "README.md"
requires-python = ">=3.14" # t-strings
dependencies = []

[project.scripts]
bast3st = "bast3st.cli:run"


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["bast3st"]  #, "bast3st_cli"]
package-dir = {"" = "src"}

